# ruff: noqa: E501, I001
# generated by datamodel-codegen:
#   filename:  _internal

from __future__ import annotations

from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel, constr

from . import brief as brief_1


class QuestionType(StrEnum):
    fact_reconstruction = 'fact_reconstruction'
    identity_inference = 'identity_inference'
    causal_explanation = 'causal_explanation'
    path_discovery = 'path_discovery'
    rule_discovery = 'rule_discovery'
    relationship_inference = 'relationship_inference'
    decision_reasoning = 'decision_reasoning'


class ConclusionMode(StrEnum):
    unique = 'unique'
    finite_multiple = 'finite_multiple'
    optimal = 'optimal'
    probabilistic = 'probabilistic'
    open_interpretation = 'open_interpretation'
    multiple_endings = 'multiple_endings'
    undetermined = 'undetermined'


class ValueType(StrEnum):
    entity_or_claim_ref = 'entity_or_claim_ref'
    text_or_claim_ref = 'text_or_claim_ref'
    object_ref = 'object_ref'
    text = 'text'
    number = 'number'
    boolean = 'boolean'


class RequiredSlot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    slot_id: Annotated[str, Field(pattern='^slot_[a-z0-9][a-z0-9_]{0,55}$')]
    value_type: ValueType
    required: bool


class AcceptedAnswers(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Tag(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ConfirmationStatus(StrEnum):
    user_confirmed = 'user_confirmed'
    ai_inferred = 'ai_inferred'
    unresolved = 'unresolved'


class ActorType(StrEnum):
    user = 'user'
    agent = 'agent'
    system = 'system'


class ActorRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    actor_type: ActorType
    actor_id: Annotated[
        str, Field(pattern='^(?:user|agent|system)_[a-z0-9][a-z0-9_]{0,55}$')
    ]


class ObjectType(StrEnum):
    casefile = 'casefile'
    resolution_spec = 'resolution_spec'
    entity = 'entity'
    relationship = 'relationship'
    location = 'location'
    event = 'event'
    information_unit = 'information_unit'
    claim = 'claim'
    hypothesis = 'hypothesis'
    reasoning_path = 'reasoning_path'
    constraint = 'constraint'
    structure_lock = 'structure_lock'
    source_fragment = 'source_fragment'


class ObjectRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    object_type: ObjectType
    object_id: Annotated[str, Field(max_length=64, min_length=5)]


class ObjectRefList(RootModel[list[ObjectRef]]):
    root: list[ObjectRef]


class CoreMetadata(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    description: str | None = None
    tags: list[Tag]
    source_refs: list[ObjectRef]
    confidence: Annotated[float | None, Field(ge=0.0, le=1.0)]
    confirmation_status: ConfirmationStatus
    created_by: ActorRef
    updated_at: AwareDatetime
    revision: Annotated[int, Field(ge=1)]


class Extensions(
    RootModel[dict[constr(pattern=r'^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$'), Any]]
):
    root: Annotated[
        dict[constr(pattern=r'^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$'), Any],
        Field(title='Extensions'),
    ]


class RuleId(RootModel[str]):
    root: Annotated[str, Field(pattern='^CF-S[012]-[A-Z0-9]+(?:-[A-Z0-9]+)*-[0-9]{3}$')]


class JsonPointer(RootModel[str]):
    root: Annotated[str, Field(pattern='^(?:/(?:[^~/]|~[01])*)*$')]


class SchematicSpatialPosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    coordinate_system: Literal['schematic']
    x: Annotated[float, Field(ge=0.0, le=100.0)]
    y: Annotated[float, Field(ge=0.0, le=100.0)]
    scene_id: Annotated[str | None, Field(pattern='^scn_[a-z0-9][a-z0-9_]{0,56}$')] = (
        None
    )
    floor_id: Annotated[str | None, Field(pattern='^floor_[a-z0-9][a-z0-9_]{0,54}$')] = (
        None
    )


class Wgs84SpatialPosition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    coordinate_system: Literal['wgs84']
    latitude: Annotated[float, Field(ge=-90.0, le=90.0)]
    longitude: Annotated[float, Field(ge=-180.0, le=180.0)]


class ScenePoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    x: Annotated[float, Field(ge=0.0, le=100.0)]
    y: Annotated[float, Field(ge=0.0, le=100.0)]


class Wgs84RoutePoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    latitude: Annotated[float, Field(ge=-90.0, le=90.0)]
    longitude: Annotated[float, Field(ge=-180.0, le=180.0)]


class SpatialSceneFloor(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    floor_id: Annotated[str, Field(pattern='^floor_[a-z0-9][a-z0-9_]{0,54}$')]
    label: Annotated[str, Field(min_length=1)]
    background_image_url: Annotated[str | None, Field(min_length=1)] = None
    image_width: Annotated[float | None, Field(gt=0.0)] = None
    image_height: Annotated[float | None, Field(gt=0.0)] = None


class SpatialSceneRegion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    region_id: Annotated[str, Field(pattern='^region_[a-z0-9][a-z0-9_]{0,51}$')]
    name: Annotated[str, Field(min_length=1)]
    geometry: Annotated[list[ScenePoint], Field(min_length=3)]


class SpatialScene(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    scene_id: Annotated[str, Field(pattern='^scn_[a-z0-9][a-z0-9_]{0,56}$')]
    name: Annotated[str, Field(min_length=1)]
    background_image_url: Annotated[str | None, Field(min_length=1)] = None
    image_width: Annotated[float | None, Field(gt=0.0)] = None
    image_height: Annotated[float | None, Field(gt=0.0)] = None
    floors: list[SpatialSceneFloor] | None = None
    regions: list[SpatialSceneRegion] | None = None


class Wgs84RouteGeometry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    coordinate_system: Literal['wgs84']
    points: Annotated[list[Wgs84RoutePoint], Field(min_length=2)]


class SchematicRouteGeometry(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    coordinate_system: Literal['schematic']
    points: Annotated[list[ScenePoint], Field(min_length=2)]


class RouteGeometry(RootModel[Wgs84RouteGeometry | SchematicRouteGeometry]):
    root: Annotated[
        Wgs84RouteGeometry | SchematicRouteGeometry,
        Field(
            description='Source-derived route polyline; the coordinate system must match the map mode where it is rendered.',
            title='RouteGeometry',
        ),
    ]


class WallClockTime(RootModel[str]):
    root: Annotated[
        str,
        Field(
            description='Timezone-free in-world wall-clock time. Precision is encoded without fabricated lower-order fields.',
            pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}(?::[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,6})?)?)?)?$',
            title='WallClockTime',
        ),
    ]


class TemporalPrecision(StrEnum):
    second = 'second'
    minute = 'minute'
    hour = 'hour'
    day = 'day'


class TemporalPosition1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['exact']
    value: Annotated[
        str,
        Field(
            description='Timezone-free in-world wall-clock time. Precision is encoded without fabricated lower-order fields.',
            pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}(?::[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,6})?)?)?)?$',
            title='WallClockTime',
        ),
    ]
    precision: TemporalPrecision


class TemporalPosition2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['approximate']
    value: Annotated[
        str,
        Field(
            description='Timezone-free in-world wall-clock time. Precision is encoded without fabricated lower-order fields.',
            pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}(?::[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,6})?)?)?)?$',
            title='WallClockTime',
        ),
    ]
    precision: TemporalPrecision


class TemporalPosition3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['range']
    start: Annotated[
        str,
        Field(
            description='Timezone-free in-world wall-clock time. Precision is encoded without fabricated lower-order fields.',
            pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}(?::[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,6})?)?)?)?$',
            title='WallClockTime',
        ),
    ]
    end: Annotated[
        str,
        Field(
            description='Timezone-free in-world wall-clock time. Precision is encoded without fabricated lower-order fields.',
            pattern='^[0-9]{4}-[0-9]{2}-[0-9]{2}(?:T[0-9]{2}(?::[0-9]{2}(?::[0-9]{2}(?:\\.[0-9]{1,6})?)?)?)?$',
            title='WallClockTime',
        ),
    ]
    precision: TemporalPrecision


class Relation(StrEnum):
    before = 'before'
    after = 'after'
    same_time = 'same_time'


class TemporalPosition4(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['relative']
    anchor_event_ref: ObjectRef
    relation: Relation
    offset_minutes: Annotated[float | None, Field(ge=0.0)]


class TemporalPosition5(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    kind: Literal['unknown']


class TemporalPosition(
    RootModel[
        TemporalPosition1
        | TemporalPosition2
        | TemporalPosition3
        | TemporalPosition4
        | TemporalPosition5
    ]
):
    root: Annotated[
        TemporalPosition1 | TemporalPosition2 | TemporalPosition3 | TemporalPosition4 | TemporalPosition5,
        Field(title='TemporalPosition'),
    ]


class Outcome(StrEnum):
    answer = 'answer'
    undetermined = 'undetermined'


class ReviewStatus(StrEnum):
    proposed = 'proposed'
    confirmed = 'confirmed'


class Value1(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Value(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    slot_id: Annotated[str, Field(pattern='^slot_[a-z0-9][a-z0-9_]{0,55}$')]
    value: Value1 | float | bool | ObjectRef


class UnresolvedGap(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class ResolutionConclusion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    outcome: Outcome
    review_status: ReviewStatus
    summary: Annotated[str, Field(min_length=1)]
    values: list[Value]
    selected_hypothesis_refs: list[ObjectRef]
    supporting_reasoning_path_refs: list[ObjectRef]
    rationale: Annotated[str, Field(min_length=1)]
    unresolved_gaps: list[UnresolvedGap]


class EntityType(StrEnum):
    person = 'person'
    organization = 'organization'
    object = 'object'
    system = 'system'
    faction = 'faction'
    rule_actor = 'rule_actor'
    other = 'other'


class Alias(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Trait(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Goal(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Secret(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Capability(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class KnowledgeState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    as_of_event_ref: ObjectRef | None
    knows_refs: list[ObjectRef]
    believes_refs: list[ObjectRef]
    false_belief_refs: list[ObjectRef]


class Entity(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^ent_[a-z0-9][a-z0-9_]{0,56}$')]
    entity_type: EntityType
    name: Annotated[str, Field(min_length=1)]
    aliases: list[Alias]
    traits: list[Trait]
    goals: list[Goal]
    secrets: list[Secret]
    capabilities: list[Capability]
    knowledge_states: list[KnowledgeState]


class Direction(StrEnum):
    directed = 'directed'
    undirected = 'undirected'
    bidirectional = 'bidirectional'


class TruthStatus(StrEnum):
    canon_true = 'canon_true'
    reported = 'reported'
    disputed = 'disputed'
    false_belief = 'false_belief'
    unknown = 'unknown'


class Visibility(StrEnum):
    public = 'public'
    private = 'private'
    restricted = 'restricted'
    hidden = 'hidden'


class Relationship(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^rel_[a-z0-9][a-z0-9_]{0,56}$')]
    title: Annotated[str, Field(min_length=1)]
    from_ref: ObjectRef
    to_ref: ObjectRef
    relationship_type: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    direction: Direction
    truth_status: TruthStatus
    visibility: Visibility


class AccessRule(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class TravelTime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    to_ref: ObjectRef
    minutes: Annotated[float, Field(ge=0.0)]
    route_geometry: Annotated[
        Wgs84RouteGeometry | SchematicRouteGeometry | None,
        Field(
            description='Source-derived route polyline; the coordinate system must match the map mode where it is rendered.',
            title='RouteGeometry',
        ),
    ] = None


class VisibilityRule(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Location(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^loc_[a-z0-9][a-z0-9_]{0,56}$')]
    name: Annotated[str, Field(min_length=1)]
    spatial_position: SchematicSpatialPosition | Wgs84SpatialPosition | None = None
    parent_ref: ObjectRef | None
    adjacency_refs: list[ObjectRef]
    access_rules: list[AccessRule]
    travel_times: list[TravelTime]
    visibility_rules: list[VisibilityRule]


class Event(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^evt_[a-z0-9][a-z0-9_]{0,56}$')]
    title: Annotated[str, Field(min_length=1)]
    truth_status: TruthStatus
    time: Annotated[
        TemporalPosition1 | TemporalPosition2 | TemporalPosition3 | TemporalPosition4 | TemporalPosition5,
        Field(title='TemporalPosition'),
    ]
    participant_refs: list[ObjectRef]
    location_ref: ObjectRef | None
    cause_refs: list[ObjectRef]
    effect_refs: list[ObjectRef]
    observed_by_refs: list[ObjectRef]


class InformationType(StrEnum):
    evidence = 'evidence'
    observation = 'observation'
    dialogue = 'dialogue'
    document = 'document'
    system_log = 'system_log'
    rule = 'rule'
    environment = 'environment'
    feedback = 'feedback'
    other = 'other'


class Reliability(StrEnum):
    high = 'high'
    medium = 'medium'
    low = 'low'
    unknown = 'unknown'


class AcquisitionCondition(RootModel[str]):
    root: Annotated[str, Field(min_length=1)]


class Availability(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    perspective_refs: list[ObjectRef]
    acquisition_conditions: list[AcquisitionCondition]
    alternative_path_refs: list[ObjectRef]


class Classification(StrEnum):
    key = 'key'
    supporting = 'supporting'
    background = 'background'
    distractor = 'distractor'
    misleading = 'misleading'
    incomplete = 'incomplete'


class InformationUnit(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^info_[a-z0-9][a-z0-9_]{0,55}$')]
    information_type: InformationType
    title: Annotated[str, Field(min_length=1)]
    content: Annotated[str, Field(min_length=1)]
    source_event_ref: ObjectRef | None
    reliability: Reliability
    truth_status: TruthStatus
    supports_claim_refs: list[ObjectRef]
    refutes_claim_refs: list[ObjectRef]
    availability: Availability
    classification: Classification


class ClaimType(StrEnum):
    fact = 'fact'
    causal = 'causal'
    identity = 'identity'
    relationship = 'relationship'
    temporal = 'temporal'
    rule = 'rule'
    evaluative = 'evaluative'
    other = 'other'


class Status(StrEnum):
    unsupported = 'unsupported'
    partially_supported = 'partially_supported'
    supported = 'supported'
    refuted = 'refuted'
    disputed = 'disputed'
    unresolved = 'unresolved'


class Materiality(StrEnum):
    critical = 'critical'
    major = 'major'
    minor = 'minor'
    background = 'background'


class Claim(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^claim_[a-z0-9][a-z0-9_]{0,54}$')]
    title: Annotated[str, Field(min_length=1)]
    statement: Annotated[str, Field(min_length=1)]
    claim_type: ClaimType
    support_refs: list[ObjectRef]
    refute_refs: list[ObjectRef]
    dependency_claim_refs: list[ObjectRef]
    status: Status
    materiality: Materiality


class Effect(StrEnum):
    supports = 'supports'
    contradicts = 'contradicts'
    neutral = 'neutral'


class Strength(StrEnum):
    weak = 'weak'
    moderate = 'moderate'
    strong = 'strong'


class EvidenceAssessment(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    information_ref: ObjectRef
    effect: Effect
    strength: Strength
    rationale: Annotated[str, Field(min_length=1)]


class Status1(StrEnum):
    active = 'active'
    supported = 'supported'
    eliminated = 'eliminated'
    accepted = 'accepted'
    rejected = 'rejected'
    undetermined = 'undetermined'


class Hypothesis(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^hyp_[a-z0-9][a-z0-9_]{0,56}$')]
    title: Annotated[str, Field(min_length=1)]
    proposition: Annotated[str, Field(min_length=1)]
    target_resolution_ref: ObjectRef
    required_claim_refs: list[ObjectRef]
    falsifier_refs: list[ObjectRef]
    competing_hypothesis_refs: list[ObjectRef]
    evidence_assessments: Annotated[
        list[EvidenceAssessment], Field(validate_default=True)
    ] = []
    status: Status1
    score: Annotated[float | None, Field(ge=0.0, le=1.0)]


class PathType(StrEnum):
    exclusion = 'exclusion'
    causal = 'causal'
    proof = 'proof'
    combination = 'combination'
    relationship = 'relationship'
    temporal = 'temporal'
    decision = 'decision'
    rule_derivation = 'rule_derivation'
    counterfactual = 'counterfactual'


class Operation(StrEnum):
    infer = 'infer'
    compare = 'compare'
    eliminate = 'eliminate'
    combine = 'combine'
    calculate = 'calculate'
    verify_rule = 'verify_rule'


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    step_id: Annotated[str, Field(pattern='^step_[a-z0-9][a-z0-9_]{0,55}$')]
    input_refs: list[ObjectRef]
    operation: Operation
    output_ref: ObjectRef


class ReasoningPath(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^path_[a-z0-9][a-z0-9_]{0,55}$')]
    title: Annotated[str, Field(min_length=1)]
    path_type: PathType
    target_ref: ObjectRef
    steps: Annotated[list[Step], Field(min_length=1)]
    required_for_resolution: bool
    alternative_path_refs: list[ObjectRef]


class Level(StrEnum):
    hard = 'hard'
    soft = 'soft'


class Constraint(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^con_[a-z0-9][a-z0-9_]{0,56}$')]
    title: Annotated[str, Field(min_length=1)]
    level: Level
    scope_refs: list[ObjectRef]
    statement: Annotated[str, Field(min_length=1)]
    rule_expression: str | None
    conflict_refs: list[ObjectRef]


class LockType(StrEnum):
    hard = 'hard'
    soft = 'soft'
    open = 'open'


class StructureLock(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^lock_[a-z0-9][a-z0-9_]{0,55}$')]
    title: Annotated[str, Field(min_length=1)]
    lock_type: LockType
    object_ref: ObjectRef
    field_paths: Annotated[list[JsonPointer], Field(min_length=1)]
    reason: Annotated[str, Field(min_length=1)]


class BriefIntakeFieldSource(StrEnum):
    user_original = 'user_original'
    user_confirmed = 'user_confirmed'
    agent_suggestion = 'agent_suggestion'
    unresolved = 'unresolved'


class BriefIntakeFieldSources(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    concept: BriefIntakeFieldSource
    core_selling_points: BriefIntakeFieldSource
    content_outline: BriefIntakeFieldSource
    reasoning_goal: BriefIntakeFieldSource
    resolution_mode: BriefIntakeFieldSource
    conclusion_mode: BriefIntakeFieldSource
    author_answer: BriefIntakeFieldSource
    constraints: BriefIntakeFieldSource
    scope_estimate: BriefIntakeFieldSource
    risk_notes: BriefIntakeFieldSource


class Category(StrEnum):
    must_keep = 'must_keep'
    must_avoid = 'must_avoid'
    scope = 'scope'
    cast = 'cast'
    duration = 'duration'
    content_scale = 'content_scale'
    other = 'other'


class Strength1(StrEnum):
    hard = 'hard'
    soft = 'soft'


class BriefIntakeConstraint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    constraint_key: Annotated[
        str, Field(pattern='^constraint_[a-z0-9][a-z0-9_]{0,51}$')
    ]
    category: Category
    statement: Annotated[str, Field(max_length=1000, min_length=1)]
    strength: Strength1
    confirmed: bool
    source: BriefIntakeFieldSource


class BriefIntakePendingDecision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    decision_key: Annotated[str, Field(pattern='^decision_[a-z0-9][a-z0-9_]{0,53}$')]
    prompt: Annotated[str, Field(max_length=1000, min_length=1)]
    impact: Annotated[str, Field(max_length=1000, min_length=1)]
    source: Literal['unresolved']


class Suggestion(RootModel[str]):
    root: Annotated[str, Field(max_length=1000, min_length=1)]


class BriefIntakeQuestion(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    question_key: Annotated[str, Field(pattern='^question_[a-z0-9][a-z0-9_]{0,53}$')]
    ordinal: Annotated[int, Field(ge=1, le=2)]
    prompt: Annotated[str, Field(max_length=1000, min_length=1)]
    impact: Annotated[str, Field(max_length=1000, min_length=1)]
    required: bool
    suggestions: Annotated[list[Suggestion], Field(max_length=3)]


class BriefIntakeQuestionSet(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    questions: Annotated[list[BriefIntakeQuestion], Field(max_length=2)]


class Op(StrEnum):
    add = 'add'
    remove = 'remove'
    replace_ = 'replace'


class PatchOperation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    operation_id: Annotated[str, Field(pattern='^op_[a-z0-9][a-z0-9_]{0,57}$')]
    op: Op
    target_ref: ObjectRef
    path: Annotated[str, Field(pattern='^(?:/(?:[^~/]|~[01])*)*$')]
    expected_revision: Annotated[int | None, Field(ge=1)]
    old_value: Any
    new_value: Any


class TaskType(StrEnum):
    brief_polish = 'brief_polish'
    brief_anchor_extract = 'brief_anchor_extract'
    brief_intake_questions = 'brief_intake_questions'
    brief_intake_synthesize = 'brief_intake_synthesize'
    brief_strategy_options = 'brief_strategy_options'
    brief_to_draft = 'brief_to_draft'
    casefile_chat = 'casefile_chat'
    reverse_parse = 'reverse_parse'
    idea_generation = 'idea_generation'


class Status2(StrEnum):
    queued = 'queued'
    running = 'running'
    cancelling = 'cancelling'
    succeeded = 'succeeded'
    failed = 'failed'
    cancelled = 'cancelled'


class Provider(StrEnum):
    openai = 'openai'
    deepseek = 'deepseek'


class InputBriefRevision(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class InputSourceRecordId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class InputBriefIntakeId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class InputBriefIntakeRevision(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class BaseBriefIntakeCandidateId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class AgentThreadId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class InputMessageId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class OutputMessageId(RootModel[int]):
    root: Annotated[int, Field(ge=1)]


class CandidateStrategy(StrEnum):
    structure_first = 'structure_first'
    atmosphere_first = 'atmosphere_first'
    reasoning_first = 'reasoning_first'
    balanced = 'balanced'


class TaskFailureIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    path: Annotated[str, Field(max_length=512)]
    message: Annotated[str, Field(max_length=240, min_length=1)]


class TaskFailure(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    code: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    message: Annotated[str, Field(max_length=320, min_length=1)]
    retryable: bool
    issues: list[TaskFailureIssue]


class AgentDiagnosticIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    component_id: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    failure_layer: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    schema_id: str | None
    code: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    path: Annotated[str, Field(max_length=512)]
    message: Annotated[str, Field(max_length=240, min_length=1)]


class Status3(StrEnum):
    pending = 'pending'
    running = 'running'
    succeeded = 'succeeded'
    failed = 'failed'
    reused = 'reused'
    skipped = 'skipped'


class AgentComponentStepView(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    step_run_id: Annotated[int, Field(ge=1)]
    attempt_no: Annotated[int, Field(ge=1)]
    component_id: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    parent_component_id: str | None
    execution_no: Annotated[int, Field(ge=1)]
    status: Status3
    schema_id: Annotated[str, Field(min_length=1)]
    input_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    output_hash: Annotated[str | None, Field(pattern='^[0-9a-f]{64}$')]
    failure_layer: str | None
    issues: list[AgentDiagnosticIssue]
    recoverable: bool
    resumed_from_step_run_id: Annotated[int | None, Field(ge=1)]


class Strategy(StrEnum):
    structure_first = 'structure_first'
    atmosphere_first = 'atmosphere_first'
    reasoning_first = 'reasoning_first'


class Strength2(RootModel[str]):
    root: Annotated[str, Field(max_length=240, min_length=1)]


class Tradeoff(RootModel[str]):
    root: Annotated[str, Field(max_length=240, min_length=1)]


class BriefStrategyOption(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    strategy: Strategy
    direction: Annotated[str, Field(max_length=600, min_length=1)]
    focus: Annotated[str, Field(max_length=300, min_length=1)]
    strengths: Annotated[list[Strength2], Field(max_length=3, min_length=2)]
    tradeoffs: Annotated[list[Tradeoff], Field(max_length=2, min_length=1)]
    brief_fit: Annotated[str, Field(max_length=400, min_length=1)]


class RecommendedStrategy(StrEnum):
    structure_first = 'structure_first'
    atmosphere_first = 'atmosphere_first'
    reasoning_first = 'reasoning_first'


class BriefStrategyOptionsResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    input_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    strategy_version: Literal['candidate-strategy-v1']
    options: Annotated[list[BriefStrategyOption], Field(max_length=3, min_length=3)]
    recommended_strategy: RecommendedStrategy
    recommendation_reason: Annotated[str, Field(max_length=400, min_length=1)]


class TaskRun(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    task_run_id: Annotated[int, Field(ge=1)]
    project_id: Annotated[int, Field(ge=1)]
    task_type: TaskType
    status: Status2
    stage: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    provider: Provider
    model_id: Annotated[str, Field(min_length=1)]
    input_draft_revision: Annotated[int, Field(ge=1)]
    input_brief_revision: InputBriefRevision | None
    input_source_record_id: InputSourceRecordId | None
    input_brief_intake_id: InputBriefIntakeId | None
    input_brief_intake_revision: InputBriefIntakeRevision | None
    base_brief_intake_candidate_id: BaseBriefIntakeCandidateId | None
    agent_thread_id: AgentThreadId | None
    input_message_id: InputMessageId | None
    output_message_id: OutputMessageId | None
    input_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]
    candidate_strategy: CandidateStrategy | None
    attempt_count: Annotated[int, Field(ge=0)]
    usage: dict[str, Any]
    result: dict[str, Any] | None
    result_snapshot_id: Annotated[int | None, Field(ge=1)] = None
    error_code: str | None = None
    failure: TaskFailure | None
    component_steps: list[AgentComponentStepView]
    created_at: AwareDatetime | None = None
    updated_at: AwareDatetime | None = None


class TaskEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    event_id: Annotated[int, Field(ge=1)]
    task_run_id: Annotated[int, Field(ge=1)]
    sequence_no: Annotated[int, Field(ge=1)]
    event_type: Annotated[str, Field(pattern='^[a-z][a-z0-9_.]*$')]
    stage: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    payload: dict[str, Any]
    occurred_at: AwareDatetime


class AgentGenerateRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    project_id: Annotated[int, Field(ge=1)]
    brief_version_id: Annotated[int, Field(ge=1)]
    expected_draft_id: Annotated[int, Field(ge=1)]
    expected_draft_revision: Annotated[int, Field(ge=1)]
    provider: Provider


class AgentGenerateResult(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    task_run_id: Annotated[int, Field(ge=1)]
    status: Literal['succeeded']
    snapshot_id: Annotated[int, Field(ge=1)]
    draft_revision: Annotated[int, Field(ge=1)]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class Sha256Hex(RootModel[str]):
    root: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class StableKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=160, min_length=1, pattern='^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$'
        ),
    ]


class NamespacedKey(RootModel[str]):
    root: Annotated[
        str,
        Field(
            max_length=160,
            min_length=3,
            pattern='^[a-z][a-z0-9]*[._-][a-z0-9]+(?:[._-][a-z0-9]+)*$',
        ),
    ]


class ArtifactKind(StrEnum):
    input_manifest = 'input_manifest'
    narrative_ir = 'narrative_ir'
    novel_plan = 'novel_plan'
    exposure_schedule = 'exposure_schedule'
    scene_plan = 'scene_plan'
    scene_context = 'scene_context'
    scene_render = 'scene_render'
    scene_assertions = 'scene_assertions'
    validation_report = 'validation_report'
    source_map = 'source_map'
    novel_candidate = 'novel_candidate'
    compile_manifest = 'compile_manifest'


class CompilerDiagnosticSeverity(StrEnum):
    info = 'info'
    warning = 'warning'
    error = 'error'


class CompileMode(StrEnum):
    preview = 'preview'
    canonical = 'canonical'


class CompilerSourceRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    object_ref: ObjectRef
    field_path: Annotated[str, Field(pattern='^(?:/(?:[^~/]|~[01])*)*$')]
    source_fragment_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class CompilerArtifactRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    artifact_kind: ArtifactKind
    artifact_key: Annotated[
        str,
        Field(
            max_length=160,
            min_length=3,
            pattern='^[a-z][a-z0-9]*[._-][a-z0-9]+(?:[._-][a-z0-9]+)*$',
        ),
    ]
    schema_id: Annotated[
        str,
        Field(
            max_length=160,
            min_length=3,
            pattern='^[a-z][a-z0-9]*[._-][a-z0-9]+(?:[._-][a-z0-9]+)*$',
        ),
    ]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class CompilerDiagnostic(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    severity: CompilerDiagnosticSeverity
    code: Annotated[
        str,
        Field(
            max_length=160, min_length=1, pattern='^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$'
        ),
    ]
    message: Annotated[str, Field(max_length=2000, min_length=1)]
    artifact_ref: CompilerArtifactRef | None = None
    source_refs: list[CompilerSourceRef]


class CompilerProfileBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    profile_key: Annotated[
        str,
        Field(
            max_length=160, min_length=1, pattern='^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$'
        ),
    ]
    profile_schema_id: Annotated[
        str,
        Field(
            max_length=160,
            min_length=3,
            pattern='^[a-z][a-z0-9]*[._-][a-z0-9]+(?:[._-][a-z0-9]+)*$',
        ),
    ]
    profile_version: Annotated[int, Field(ge=1)]
    frozen_payload: dict[str, Any]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class SnapshotBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    snapshot_id: Annotated[int, Field(ge=1)]
    draft_id: Annotated[int, Field(ge=1)]
    snapshot_revision: Annotated[int, Field(ge=1)]
    schema_version: Annotated[str, Field(max_length=32, min_length=1)]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class CanonBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    canon_version_id: Annotated[int, Field(ge=1)]
    source_snapshot_id: Annotated[int, Field(ge=1)]
    version_no: Annotated[int, Field(ge=1)]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class ExposureBinding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    draft_id: Annotated[int, Field(ge=1)]
    plan_revision_id: Annotated[int, Field(ge=1)]
    revision_no: Annotated[int, Field(ge=1)]
    frozen_payload: dict[str, Any]
    content_hash: Annotated[str, Field(pattern='^[0-9a-f]{64}$')]


class CompileInputManifest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    target: Literal['novel']
    mode: CompileMode
    source_snapshot: SnapshotBinding
    source_canon: CanonBinding | None
    exposure: ExposureBinding | None
    profile: CompilerProfileBinding
    compiler_version: Annotated[
        str,
        Field(
            max_length=160, min_length=1, pattern='^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)*$'
        ),
    ]


class ResolutionSpec(CoreMetadata):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    id: Annotated[str, Field(pattern='^res_[a-z0-9][a-z0-9_]{0,56}$')]
    title: Annotated[str, Field(min_length=1)]
    question_type: QuestionType
    reasoning_question: Annotated[str, Field(min_length=1)]
    conclusion_mode: ConclusionMode
    required_slots: list[RequiredSlot]
    conclusion: ResolutionConclusion | None = None
    accepted_answers: list[AcceptedAnswers | ObjectRef]
    required_claim_refs: list[ObjectRef]


class EditingContracts(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    casefile: Schema_1
    brief: brief_1.Schema
    brief_intake_candidate: Schema
    brief_intake_question_set: BriefIntakeQuestionSet
    validation_issue: Schema_3
    patch_candidate: Schema_2
    task_run: TaskRun
    task_event: TaskEvent
    agent_generate_request: AgentGenerateRequest
    agent_generate_result: AgentGenerateResult
    compiler_source_ref: CompilerSourceRef
    compiler_artifact_ref: CompilerArtifactRef
    compiler_diagnostic: CompilerDiagnostic
    compiler_profile_binding: CompilerProfileBinding
    compile_input_manifest: CompileInputManifest


class CoreSellingPoint(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class ContentOutlineItem(RootModel[str]):
    root: Annotated[str, Field(max_length=1000, min_length=1)]


class ResolutionMode(StrEnum):
    author_anchored = 'author_anchored'
    agent_proposed = 'agent_proposed'
    open = 'open'


class ConclusionMode_1(StrEnum):
    unique = 'unique'
    finite_multiple = 'finite_multiple'
    optimal = 'optimal'
    probabilistic = 'probabilistic'
    open_interpretation = 'open_interpretation'
    multiple_endings = 'multiple_endings'
    undetermined = 'undetermined'


class AuthorAnswer(RootModel[str]):
    root: Annotated[str, Field(max_length=4000, min_length=1)]


class ScopeEstimate(RootModel[str]):
    root: Annotated[str, Field(max_length=1000, min_length=1)]


class RiskNote(RootModel[str]):
    root: Annotated[str, Field(max_length=500, min_length=1)]


class Schema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    concept: Annotated[str, Field(max_length=1000, min_length=1)]
    core_selling_points: Annotated[list[CoreSellingPoint], Field(max_length=8)]
    content_outline: Annotated[list[ContentOutlineItem], Field(max_length=16)]
    reasoning_goal: Annotated[str, Field(max_length=2000, min_length=1)]
    resolution_mode: ResolutionMode
    conclusion_mode: ConclusionMode_1
    author_answer: AuthorAnswer | None
    constraints: Annotated[list[BriefIntakeConstraint], Field(max_length=40)]
    pending_decisions: Annotated[list[BriefIntakePendingDecision], Field(max_length=20)]
    scope_estimate: ScopeEstimate | None
    risk_notes: Annotated[list[RiskNote], Field(max_length=12)]
    field_sources: BriefIntakeFieldSources


class Status_1(StrEnum):
    draft = 'draft'
    canon = 'canon'
    archived = 'archived'


class ParentVersionId(RootModel[str]):
    root: Annotated[str, Field(pattern='^cv_[a-z0-9][a-z0-9_]{0,56}$')]


class Version(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    version_id: Annotated[
        str, Field(pattern='^(?:draft|snapshot|cv)_[a-z0-9][a-z0-9_]{0,54}$')
    ]
    version_no: Annotated[int, Field(ge=1)]
    parent_version_id: ParentVersionId | None


class BriefRef(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    brief_id: Annotated[str, Field(pattern='^brief_[a-z0-9][a-z0-9_]{0,54}$')]
    version: Annotated[int, Field(ge=1)]


class Severity(StrEnum):
    low = 'low'
    medium = 'medium'
    high = 'high'


class ContentNotice(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    notice_id: Annotated[str, Field(pattern='^notice_[a-z0-9][a-z0-9_]{0,53}$')]
    category: Annotated[str, Field(pattern='^[a-z][a-z0-9_]*$')]
    severity: Severity
    description: Annotated[str, Field(min_length=1)]


class Schema_1(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['2.0']
    casefile_id: Annotated[str, Field(pattern='^case_[a-z0-9][a-z0-9_]{0,55}$')]
    title: Annotated[str, Field(min_length=1)]
    status: Status_1
    version: Version
    brief_ref: BriefRef
    resolution_specs: list[ResolutionSpec]
    entities: list[Entity]
    relationships: list[Relationship]
    locations: list[Location]
    spatial_scenes: list[SpatialScene] | None = None
    events: list[Event]
    information_units: list[InformationUnit]
    claims: list[Claim]
    hypotheses: list[Hypothesis]
    reasoning_paths: list[ReasoningPath]
    constraints: list[Constraint]
    structure_locks: list[StructureLock]
    content_notices: list[ContentNotice]
    extensions: Annotated[
        dict[constr(pattern=r'^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$'), Any],
        Field(title='Extensions'),
    ]


class IssueRef(RootModel[str]):
    root: Annotated[str, Field(pattern='^issue_[a-z0-9][a-z0-9_]{0,54}$')]


class ApprovalStatus(StrEnum):
    pending = 'pending'
    approved = 'approved'
    rejected = 'rejected'
    superseded = 'superseded'


class Schema_2(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['2.0']
    patch_id: Annotated[str, Field(pattern='^patch_[a-z0-9][a-z0-9_]{0,54}$')]
    base_version_id: Annotated[
        str, Field(pattern='^(?:draft|snapshot|cv)_[a-z0-9][a-z0-9_]{0,54}$')
    ]
    reason_summary: Annotated[str, Field(min_length=1)]
    issue_refs: list[IssueRef]
    operations: Annotated[list[PatchOperation], Field(min_length=1)]
    affected_refs: list[ObjectRef]
    expected_resolved_rule_ids: list[RuleId]
    approval_status: ApprovalStatus
    created_by: ActorRef
    created_at: AwareDatetime
    extensions: Annotated[
        dict[constr(pattern=r'^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$'), Any],
        Field(title='Extensions'),
    ]


class Severity_1(StrEnum):
    s0 = 'S0'
    s1 = 'S1'
    s2 = 'S2'


class DetectionType(StrEnum):
    deterministic = 'deterministic'
    graph = 'graph'
    model_assisted = 'model_assisted'
    manual = 'manual'


class Status_2(StrEnum):
    open = 'open'
    accepted_risk = 'accepted_risk'
    resolved = 'resolved'
    dismissed = 'dismissed'


class Schema_3(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    schema_version: Literal['2.0']
    issue_id: Annotated[str, Field(pattern='^issue_[a-z0-9][a-z0-9_]{0,54}$')]
    rule_id: Annotated[
        str, Field(pattern='^CF-S[012]-[A-Z0-9]+(?:-[A-Z0-9]+)*-[0-9]{3}$')
    ]
    severity: Severity_1
    title: Annotated[str, Field(min_length=1)]
    object_refs: Annotated[list[ObjectRef], Field(min_length=1)]
    evidence_refs: list[ObjectRef]
    explanation: Annotated[str, Field(min_length=1)]
    impact_refs: list[ObjectRef]
    fix_hint: Annotated[str, Field(min_length=1)]
    detection_type: DetectionType
    status: Status_2
    validator_version: Annotated[str, Field(pattern='^[0-9]+\\.[0-9]+\\.[0-9]+$')]
    extensions: Annotated[
        dict[constr(pattern=r'^[a-z][a-z0-9]*(?:[._-][a-z0-9]+)+$'), Any],
        Field(title='Extensions'),
    ]
