# ruff: noqa: E501, I001
# generated by datamodel-codegen:
#   filename:  editing-contracts.schema.json

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class Schema(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        populate_by_name=True,
    )
    concept: Annotated[str, Field(max_length=200, min_length=1)]
    rationale: Annotated[str, Field(max_length=1500, min_length=1)]
    chapters: Annotated[int, Field(ge=1, le=30)]
    scenes: Annotated[int, Field(ge=1, le=120)]
    style: Annotated[str, Field(max_length=2000, min_length=1)]
