"""Exact business-table inventory shared by foundation migration checks."""

BUSINESS_TABLES = {
    "agent_model_calls",
    "agent_messages",
    "agent_patch_operations",
    "agent_patch_sets",
    "agent_threads",
    "agent_step_runs",
    "agent_thread_context_states",
    "audit_events",
    "brief_intake_candidates",
    "brief_intake_questions",
    "brief_intakes",
    "brief_versions",
    "briefs",
    "canon_versions",
    "casefile_constraints",
    "casefile_contract_refs",
    "casefile_objects",
    "casefile_refs",
    "casefiles",
    "claims",
    "draft_operations",
    "draft_snapshots",
    "drafts",
    "entities",
    "events",
    "evidence_items",
    "exposure_plan_entries",
    "exposure_plan_entry_refs",
    "exposure_plan_revisions",
    "exposure_plans",
    "hypotheses",
    "idea_candidates",
    "imported_documents",
    "information_units",
    "knowledge_state_entries",
    "knowledge_states",
    "locations",
    "narrative_phases",
    "parse_items",
    "people",
    "projects",
    "reasoning_edges",
    "reasoning_nodes",
    "reasoning_paths",
    "relationships",
    "resolution_slots",
    "resolution_specs",
    "source_records",
    "structure_locks",
    "task_attempts",
    "task_events",
    "task_runs",
    "testimonies",
    "user_provider_settings",
    "users",
}


__all__ = ["BUSINESS_TABLES"]
