"""Shared SQLAlchemy metadata and persistence mixins."""

from datetime import datetime

from sqlalchemy import BigInteger, DateTime, FetchedValue, Identity, MetaData, text
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

NAMING_CONVENTION = {
    "ix": "ix_%(table_name)s_%(column_0_N_name)s",
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """Declarative base shared by every PostgreSQL model."""

    metadata = MetaData(naming_convention=NAMING_CONVENTION)


class BigIntIdentityPrimaryKeyMixin:
    """Database-generated ``BIGINT GENERATED BY DEFAULT AS IDENTITY`` key."""

    id: Mapped[int] = mapped_column(
        BigInteger,
        Identity(always=False),
        primary_key=True,
    )


class TimestampMixin:
    """Creation and database-trigger-maintained modification timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("CURRENT_TIMESTAMP"),
        server_onupdate=FetchedValue(),
    )
