"""Versioned novel collaboration, isolated from compilation."""

import sqlalchemy as sa
from alembic import op

revision = "20260908161410"
down_revision = "20260908121826"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "novel_manuscripts",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("casefile_id", sa.BigInteger(), nullable=False),
        sa.Column("draft_id", sa.BigInteger(), nullable=False),
        sa.Column("source_key", sa.String(length=160), nullable=False),
        sa.Column("source_label", sa.String(length=200), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint("revision >= 1", name=op.f("ck_novel_manuscripts_revision_positive")),
        sa.ForeignKeyConstraint(
            ["project_id", "casefile_id", "draft_id"],
            ["drafts.project_id", "drafts.casefile_id", "drafts.id"],
            name=op.f("fk_novel_manuscripts_project_id_casefile_id_draft_id_drafts"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name=op.f("fk_novel_manuscripts_project_id_projects")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_manuscripts")),
        sa.UniqueConstraint(
            "project_id",
            "draft_id",
            "source_key",
            name=op.f("uq_novel_manuscripts_project_id_draft_id_source_key"),
        ),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_novel_manuscripts_project_id_id")),
    )
    op.create_table(
        "novel_versions",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("manuscript_id", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("reason", sa.String(length=100), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "manuscript_id"],
            ["novel_manuscripts.project_id", "novel_manuscripts.id"],
            name=op.f("fk_novel_versions_project_id_manuscript_id_novel_manuscripts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_versions")),
        sa.UniqueConstraint(
            "manuscript_id", "revision", name=op.f("uq_novel_versions_manuscript_id_revision")
        ),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_novel_versions_project_id_id")),
        sa.UniqueConstraint(
            "project_id",
            "manuscript_id",
            "revision",
            name=op.f("uq_novel_versions_project_id_manuscript_id_revision"),
        ),
    )
    op.create_table(
        "novel_chapters",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("chapter_key", sa.String(length=100), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id", "version_id"],
            ["novel_versions.project_id", "novel_versions.id"],
            name=op.f("fk_novel_chapters_project_id_version_id_novel_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_chapters")),
        sa.UniqueConstraint(
            "version_id", "chapter_key", name=op.f("uq_novel_chapters_version_id_chapter_key")
        ),
        sa.UniqueConstraint(
            "version_id", "ordinal", name=op.f("uq_novel_chapters_version_id_ordinal")
        ),
    )
    op.create_table(
        "novel_exchanges",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("manuscript_id", sa.BigInteger(), nullable=False),
        sa.Column("revision", sa.BigInteger(), nullable=False),
        sa.Column("request_key", sa.String(length=100), nullable=False),
        sa.Column("task_id", sa.BigInteger(), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("chapter_key", sa.String(length=100), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "mode IN ('discuss','rewrite','polish')", name=op.f("ck_novel_exchanges_mode_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "manuscript_id", "revision"],
            [
                "novel_versions.project_id",
                "novel_versions.manuscript_id",
                "novel_versions.revision",
            ],
            name=op.f("fk_novel_exchanges_project_id_manuscript_id_revision_novel_versions"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "task_id"],
            ["task_runs.project_id", "task_runs.id"],
            name=op.f("fk_novel_exchanges_project_id_task_id_task_runs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_exchanges")),
        sa.UniqueConstraint(
            "manuscript_id",
            "request_key",
            name=op.f("uq_novel_exchanges_manuscript_id_request_key"),
        ),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_novel_exchanges_project_id_id")),
        sa.UniqueConstraint("task_id", name=op.f("uq_novel_exchanges_task_id")),
    )
    op.create_table(
        "novel_edits",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("exchange_id", sa.BigInteger(), nullable=False),
        sa.Column("start_offset", sa.Integer(), nullable=False),
        sa.Column("end_offset", sa.Integer(), nullable=False),
        sa.Column("before", sa.Text(), nullable=False),
        sa.Column("after", sa.Text(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "start_offset >= 0 AND end_offset > start_offset",
            name=op.f("ck_novel_edits_span_valid"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "exchange_id"],
            ["novel_exchanges.project_id", "novel_exchanges.id"],
            name=op.f("fk_novel_edits_project_id_exchange_id_novel_exchanges"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_edits")),
        sa.UniqueConstraint("project_id", "id", name=op.f("uq_novel_edits_project_id_id")),
    )
    op.create_table(
        "novel_edit_decisions",
        sa.Column("project_id", sa.BigInteger(), nullable=False),
        sa.Column("edit_id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("action", sa.String(length=20), nullable=False),
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.CheckConstraint(
            "action IN ('accept','reject')", name=op.f("ck_novel_edit_decisions_action_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "edit_id"],
            ["novel_edits.project_id", "novel_edits.id"],
            name=op.f("fk_novel_edit_decisions_project_id_edit_id_novel_edits"),
        ),
        sa.ForeignKeyConstraint(
            ["project_id", "version_id"],
            ["novel_versions.project_id", "novel_versions.id"],
            name=op.f("fk_novel_edit_decisions_project_id_version_id_novel_versions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_novel_edit_decisions")),
        sa.UniqueConstraint("edit_id", name=op.f("uq_novel_edit_decisions_edit_id")),
    )
    # ### end Alembic commands ###
    op.drop_constraint(op.f("ck_task_runs_task_type_allowed"), "task_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_task_runs_task_type_allowed"),
        "task_runs",
        "((task_type)::text = ANY ((ARRAY['brief_polish'::character varying, 'brief_a"
        "nchor_extract'::character varying, 'brief_intake_questions'::character varyi"
        "ng, 'brief_intake_synthesize'::character varying, 'brief_strategy_options'::"
        "character varying, 'brief_to_draft'::character varying, 'casefile_chat'::cha"
        "racter varying, 'reverse_parse'::character varying, 'novel_compile'::charact"
        "er varying, 'novel_collaborate'::character varying])::text[]))",
    )
    op.drop_constraint(op.f("ck_task_runs_input_matches_task_type"), "task_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_task_runs_input_matches_task_type"),
        "task_runs",
        "((((task_type)::text = 'brief_polish'::text) AND (brief_version_id IS NULL) "
        "AND (input_source_record_id IS NOT NULL) AND (input_brief_revision IS NULL) "
        "AND (brief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) AND "
        "(base_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND ("
        "input_message_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type):"
        ":text = 'brief_anchor_extract'::text) AND (brief_version_id IS NULL) AND (in"
        "put_source_record_id IS NULL) AND (input_brief_revision IS NOT NULL) AND (br"
        "ief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) AND (base_b"
        "rief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND (input_m"
        "essage_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type)::text ="
        " 'brief_intake_questions'::text) AND (brief_version_id IS NULL) AND (input_s"
        "ource_record_id IS NOT NULL) AND (input_brief_revision IS NULL) AND (brief_i"
        "ntake_id IS NOT NULL) AND (input_brief_intake_revision IS NOT NULL) AND (bas"
        "e_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND (inpu"
        "t_message_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type)::tex"
        "t = 'brief_intake_synthesize'::text) AND (brief_version_id IS NULL) AND (inp"
        "ut_source_record_id IS NOT NULL) AND (input_brief_revision IS NULL) AND (bri"
        "ef_intake_id IS NOT NULL) AND (input_brief_intake_revision IS NOT NULL) AND "
        "(agent_thread_id IS NULL) AND (input_message_id IS NULL) AND (output_message"
        "_id IS NULL)) OR (((task_type)::text = 'brief_strategy_options'::text) AND ("
        "brief_version_id IS NOT NULL) AND (input_source_record_id IS NULL) AND (inpu"
        "t_brief_revision IS NOT NULL) AND (brief_intake_id IS NULL) AND (input_brief"
        "_intake_revision IS NULL) AND (base_brief_intake_candidate_id IS NULL) AND ("
        "agent_thread_id IS NULL) AND (input_message_id IS NULL) AND (output_message_"
        "id IS NULL)) OR (((task_type)::text = 'brief_to_draft'::text) AND (brief_ver"
        "sion_id IS NOT NULL) AND (input_source_record_id IS NULL) AND (input_brief_r"
        "evision IS NOT NULL) AND (brief_intake_id IS NULL) AND (input_brief_intake_r"
        "evision IS NULL) AND (base_brief_intake_candidate_id IS NULL) AND (agent_thr"
        "ead_id IS NULL) AND (input_message_id IS NULL) AND (output_message_id IS NUL"
        "L)) OR (((task_type)::text = 'casefile_chat'::text) AND (brief_version_id IS"
        " NULL) AND (input_source_record_id IS NULL) AND (input_brief_revision IS NUL"
        "L) AND (brief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) A"
        "ND (base_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NOT NULL"
        ") AND (input_message_id IS NOT NULL) AND (output_message_id IS NOT NULL)) OR"
        " (((task_type)::text = ANY ((ARRAY['reverse_parse'::character varying, 'nove"
        "l_compile'::character varying, 'novel_collaborate'::character varying])::tex"
        "t[])) AND (brief_version_id IS NULL) AND (input_source_record_id IS NULL) AN"
        "D (input_brief_revision IS NULL) AND (brief_intake_id IS NULL) AND (input_br"
        "ief_intake_revision IS NULL) AND (base_brief_intake_candidate_id IS NULL) AN"
        "D (agent_thread_id IS NULL) AND (input_message_id IS NULL) AND (output_messa"
        "ge_id IS NULL)))",
    )
    op.execute(
        "CREATE FUNCTION reject_novel_history_mutation() RETURNS trigger LANGUAGE plp"
        "gsql AS $$ BEGIN RAISE EXCEPTION 'Novel history is immutable'; END $$"
    )
    op.execute(
        "CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON novel_versions F"
        "OR EACH ROW EXECUTE FUNCTION reject_novel_history_mutation()"
    )
    op.execute(
        "CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON novel_chapters F"
        "OR EACH ROW EXECUTE FUNCTION reject_novel_history_mutation()"
    )
    op.execute(
        "CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON novel_exchanges "
        "FOR EACH ROW EXECUTE FUNCTION reject_novel_history_mutation()"
    )
    op.execute(
        "CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON novel_edits FOR "
        "EACH ROW EXECUTE FUNCTION reject_novel_history_mutation()"
    )
    op.execute(
        "CREATE TRIGGER immutable_history BEFORE UPDATE OR DELETE ON novel_edit_decis"
        "ions FOR EACH ROW EXECUTE FUNCTION reject_novel_history_mutation()"
    )


def downgrade():
    if op.get_bind().execute(sa.text("SELECT EXISTS (SELECT 1 FROM novel_manuscripts)")).scalar():
        raise RuntimeError("Cannot downgrade while novel manuscripts exist")

    op.drop_constraint(op.f("ck_task_runs_task_type_allowed"), "task_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_task_runs_task_type_allowed"),
        "task_runs",
        "((task_type)::text = ANY ((ARRAY['brief_polish'::character varying, 'brief_a"
        "nchor_extract'::character varying, 'brief_intake_questions'::character varyi"
        "ng, 'brief_intake_synthesize'::character varying, 'brief_strategy_options'::"
        "character varying, 'brief_to_draft'::character varying, 'casefile_chat'::cha"
        "racter varying, 'reverse_parse'::character varying, 'novel_compile'::charact"
        "er varying])::text[]))",
    )
    op.drop_constraint(op.f("ck_task_runs_input_matches_task_type"), "task_runs", type_="check")
    op.create_check_constraint(
        op.f("ck_task_runs_input_matches_task_type"),
        "task_runs",
        "((((task_type)::text = 'brief_polish'::text) AND (brief_version_id IS NULL) "
        "AND (input_source_record_id IS NOT NULL) AND (input_brief_revision IS NULL) "
        "AND (brief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) AND "
        "(base_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND ("
        "input_message_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type):"
        ":text = 'brief_anchor_extract'::text) AND (brief_version_id IS NULL) AND (in"
        "put_source_record_id IS NULL) AND (input_brief_revision IS NOT NULL) AND (br"
        "ief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) AND (base_b"
        "rief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND (input_m"
        "essage_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type)::text ="
        " 'brief_intake_questions'::text) AND (brief_version_id IS NULL) AND (input_s"
        "ource_record_id IS NOT NULL) AND (input_brief_revision IS NULL) AND (brief_i"
        "ntake_id IS NOT NULL) AND (input_brief_intake_revision IS NOT NULL) AND (bas"
        "e_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND (inpu"
        "t_message_id IS NULL) AND (output_message_id IS NULL)) OR (((task_type)::tex"
        "t = 'brief_intake_synthesize'::text) AND (brief_version_id IS NULL) AND (inp"
        "ut_source_record_id IS NOT NULL) AND (input_brief_revision IS NULL) AND (bri"
        "ef_intake_id IS NOT NULL) AND (input_brief_intake_revision IS NOT NULL) AND "
        "(agent_thread_id IS NULL) AND (input_message_id IS NULL) AND (output_message"
        "_id IS NULL)) OR (((task_type)::text = 'brief_strategy_options'::text) AND ("
        "brief_version_id IS NOT NULL) AND (input_source_record_id IS NULL) AND (inpu"
        "t_brief_revision IS NOT NULL) AND (brief_intake_id IS NULL) AND (input_brief"
        "_intake_revision IS NULL) AND (base_brief_intake_candidate_id IS NULL) AND ("
        "agent_thread_id IS NULL) AND (input_message_id IS NULL) AND (output_message_"
        "id IS NULL)) OR (((task_type)::text = 'brief_to_draft'::text) AND (brief_ver"
        "sion_id IS NOT NULL) AND (input_source_record_id IS NULL) AND (input_brief_r"
        "evision IS NOT NULL) AND (brief_intake_id IS NULL) AND (input_brief_intake_r"
        "evision IS NULL) AND (base_brief_intake_candidate_id IS NULL) AND (agent_thr"
        "ead_id IS NULL) AND (input_message_id IS NULL) AND (output_message_id IS NUL"
        "L)) OR (((task_type)::text = 'casefile_chat'::text) AND (brief_version_id IS"
        " NULL) AND (input_source_record_id IS NULL) AND (input_brief_revision IS NUL"
        "L) AND (brief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) A"
        "ND (base_brief_intake_candidate_id IS NULL) AND (agent_thread_id IS NOT NULL"
        ") AND (input_message_id IS NOT NULL) AND (output_message_id IS NOT NULL)) OR"
        " (((task_type)::text = ANY ((ARRAY['reverse_parse'::character varying, 'nove"
        "l_compile'::character varying])::text[])) AND (brief_version_id IS NULL) AND"
        " (input_source_record_id IS NULL) AND (input_brief_revision IS NULL) AND (br"
        "ief_intake_id IS NULL) AND (input_brief_intake_revision IS NULL) AND (base_b"
        "rief_intake_candidate_id IS NULL) AND (agent_thread_id IS NULL) AND (input_m"
        "essage_id IS NULL) AND (output_message_id IS NULL)))",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("novel_edit_decisions")
    op.drop_table("novel_edits")
    op.drop_table("novel_exchanges")
    op.drop_table("novel_chapters")
    op.drop_table("novel_versions")
    op.drop_table("novel_manuscripts")
    # ### end Alembic commands ###
    op.execute("DROP FUNCTION reject_novel_history_mutation()")
