"""Persist bounded LLM editorial decisions without changing existing artifacts.

Revision ID: 20260908121826
Revises: 20260907210634
"""

from collections.abc import Sequence

from alembic import op

revision: str = "20260908121826"
down_revision: str | None = "20260907210634"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

OLD_IDENTITY = (
    "(COALESCE(((artifact_kind = 'input_manifest' AND artifact_key = 'compiler."
    "input_manifest' AND schema_id = 'compiler.input-manifest.v1') OR (artifact"
    "_kind = 'narrative_ir' AND artifact_key = 'compiler.narrative_ir' AND sche"
    "ma_id = 'compiler.narrative-ir.v1') OR (artifact_kind = 'novel_plan' AND a"
    "rtifact_key = 'compiler.novel_plan' AND schema_id = 'compiler.novel-plan.v"
    "1') OR (artifact_kind = 'scene_plan' AND artifact_key = 'compiler.scene_pl"
    "an' AND schema_id IN ('compiler.scene-plan.v1', 'compiler.scene-plan.v2'))"
    " OR (content_jsonb->>'schema_id' = schema_id AND ((artifact_kind = 'scene_"
    "context' AND schema_id = 'compiler.prose-judge-checklist.v1' AND artifact_"
    "key = 'compiler.scene_context.' || (content_jsonb->>'scene_id')) OR (artif"
    "act_kind = 'scene_render' AND schema_id = 'compiler.scene-render.v1' AND c"
    "ontent_jsonb->>'stage' IN ('writer','rewrite_1','rewrite_2','polished','ac"
    "cepted') AND artifact_key = 'compiler.scene_render.' || (content_jsonb->>'"
    "scene_id') || '.' || (content_jsonb->>'stage')) OR (artifact_kind = 'valid"
    "ation_report' AND schema_id = 'compiler.prose-judge-report.v1' AND content"
    "_jsonb->>'role' IN ('fidelity','adversarial','coherence','arbiter') AND ar"
    "tifact_key IN ('compiler.validation_report.' || (content_jsonb->>'scene_id"
    "') || '.semantic_0.' || (content_jsonb->>'role'),'compiler.validation_repo"
    "rt.' || (content_jsonb->>'scene_id') || '.semantic_1.' || (content_jsonb->"
    ">'role'),'compiler.validation_report.' || (content_jsonb->>'scene_id') || "
    "'.semantic_2.' || (content_jsonb->>'role'),'compiler.validation_report.' |"
    "| (content_jsonb->>'scene_id') || '.preservation.' || (content_jsonb->>'ro"
    "le'))) OR (artifact_kind = 'validation_report' AND schema_id = 'compiler.p"
    "rose-consensus-report.v1' AND artifact_key IN ('compiler.validation_report"
    ".' || (content_jsonb->>'scene_id') || '.semantic_' || (content_jsonb->>'ro"
    "und') || '.consensus', 'compiler.validation_report.' || (content_jsonb->>'"
    "scene_id') || '.preservation.consensus')) OR (artifact_kind = 'validation_"
    "report' AND schema_id = 'compiler.prose-quality-report.v1' AND ((content_j"
    "sonb->>'report_kind' = 'findings' AND artifact_key = 'compiler.validation_"
    "report.' || (content_jsonb->>'scene_id') || '.quality.findings') OR (conte"
    "nt_jsonb->>'report_kind' = 'pairwise' AND ((content_jsonb->'position_mappi"
    "ng'->>'a' = 'original' AND artifact_key = 'compiler.validation_report.' ||"
    " (content_jsonb->>'scene_id') || '.quality.pairwise.original_first') OR (c"
    "ontent_jsonb->'position_mapping'->>'a' = 'polished' AND artifact_key = 'co"
    "mpiler.validation_report.' || (content_jsonb->>'scene_id') || '.quality.pa"
    "irwise.polished_first'))))) OR (artifact_kind = 'novel_candidate' AND arti"
    "fact_key = 'compiler.novel_candidate' AND schema_id = 'compiler.novel-cand"
    "idate.v1') OR (artifact_kind = 'compile_manifest' AND artifact_key = 'comp"
    "iler.compile_manifest' AND schema_id = 'compiler.compile-manifest.v1')))),"
    " false)) OR ((artifact_kind IN ('scene_render','validation_report','compil"
    "e_manifest')) AND artifact_key ~ '\\.attempt_[1-9][0-9]*$' AND COALESCE(((a"
    "rtifact_kind = 'input_manifest' AND regexp_replace(artifact_key, '\\.attemp"
    "t_[1-9][0-9]*$', '') = 'compiler.input_manifest' AND schema_id = 'compiler"
    ".input-manifest.v1') OR (artifact_kind = 'narrative_ir' AND regexp_replace"
    "(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.narrative_ir' AND"
    " schema_id = 'compiler.narrative-ir.v1') OR (artifact_kind = 'novel_plan' "
    "AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler"
    ".novel_plan' AND schema_id = 'compiler.novel-plan.v1') OR (artifact_kind ="
    " 'scene_plan' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '"
    "') = 'compiler.scene_plan' AND schema_id IN ('compiler.scene-plan.v1', 'co"
    "mpiler.scene-plan.v2')) OR (content_jsonb->>'schema_id' = schema_id AND (("
    "artifact_kind = 'scene_context' AND schema_id = 'compiler.prose-judge-chec"
    "klist.v1' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') ="
    " 'compiler.scene_context.' || (content_jsonb->>'scene_id')) OR (artifact_k"
    "ind = 'scene_render' AND schema_id = 'compiler.scene-render.v1' AND conten"
    "t_jsonb->>'stage' IN ('writer','rewrite_1','rewrite_2','polished','accepte"
    "d') AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'comp"
    "iler.scene_render.' || (content_jsonb->>'scene_id') || '.' || (content_jso"
    "nb->>'stage')) OR (artifact_kind = 'validation_report' AND schema_id = 'co"
    "mpiler.prose-judge-report.v1' AND content_jsonb->>'role' IN ('fidelity','a"
    "dversarial','coherence','arbiter') AND regexp_replace(artifact_key, '\\.att"
    "empt_[1-9][0-9]*$', '') IN ('compiler.validation_report.' || (content_json"
    "b->>'scene_id') || '.semantic_0.' || (content_jsonb->>'role'),'compiler.va"
    "lidation_report.' || (content_jsonb->>'scene_id') || '.semantic_1.' || (co"
    "ntent_jsonb->>'role'),'compiler.validation_report.' || (content_jsonb->>'s"
    "cene_id') || '.semantic_2.' || (content_jsonb->>'role'),'compiler.validati"
    "on_report.' || (content_jsonb->>'scene_id') || '.preservation.' || (conten"
    "t_jsonb->>'role'))) OR (artifact_kind = 'validation_report' AND schema_id "
    "= 'compiler.prose-consensus-report.v1' AND regexp_replace(artifact_key, '\\"
    ".attempt_[1-9][0-9]*$', '') IN ('compiler.validation_report.' || (content_"
    "jsonb->>'scene_id') || '.semantic_' || (content_jsonb->>'round') || '.cons"
    "ensus', 'compiler.validation_report.' || (content_jsonb->>'scene_id') || '"
    ".preservation.consensus')) OR (artifact_kind = 'validation_report' AND sch"
    "ema_id = 'compiler.prose-quality-report.v1' AND ((content_jsonb->>'report_"
    "kind' = 'findings' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*"
    "$', '') = 'compiler.validation_report.' || (content_jsonb->>'scene_id') ||"
    " '.quality.findings') OR (content_jsonb->>'report_kind' = 'pairwise' AND ("
    "(content_jsonb->'position_mapping'->>'a' = 'original' AND regexp_replace(a"
    "rtifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.validation_report.'"
    " || (content_jsonb->>'scene_id') || '.quality.pairwise.original_first') OR"
    " (content_jsonb->'position_mapping'->>'a' = 'polished' AND regexp_replace("
    "artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.validation_report."
    "' || (content_jsonb->>'scene_id') || '.quality.pairwise.polished_first')))"
    ")) OR (artifact_kind = 'novel_candidate' AND regexp_replace(artifact_key, "
    "'\\.attempt_[1-9][0-9]*$', '') = 'compiler.novel_candidate' AND schema_id ="
    " 'compiler.novel-candidate.v1') OR (artifact_kind = 'compile_manifest' AND"
    " regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.co"
    "mpile_manifest' AND schema_id = 'compiler.compile-manifest.v1')))), false)"
    ") OR COALESCE((artifact_kind = 'validation_report' AND schema_id = 'compil"
    "er.prose-continuity-review.v1' AND content_jsonb->>'schema_id' = schema_id"
    " AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compile"
    "r.continuity.' || (content_jsonb->>'scene_id')), false)"
)
NEW_IDENTITY = (
    "((COALESCE(((artifact_kind = 'input_manifest' AND artifact_key = 'compiler"
    ".input_manifest' AND schema_id = 'compiler.input-manifest.v1') OR (artifac"
    "t_kind = 'narrative_ir' AND artifact_key = 'compiler.narrative_ir' AND sch"
    "ema_id = 'compiler.narrative-ir.v1') OR (artifact_kind = 'novel_plan' AND "
    "artifact_key = 'compiler.novel_plan' AND schema_id = 'compiler.novel-plan."
    "v1') OR (artifact_kind = 'scene_plan' AND artifact_key = 'compiler.scene_p"
    "lan' AND schema_id IN ('compiler.scene-plan.v1', 'compiler.scene-plan.v2')"
    ") OR (content_jsonb->>'schema_id' = schema_id AND ((artifact_kind = 'scene"
    "_context' AND schema_id = 'compiler.prose-judge-checklist.v1' AND artifact"
    "_key = 'compiler.scene_context.' || (content_jsonb->>'scene_id')) OR (arti"
    "fact_kind = 'scene_render' AND schema_id = 'compiler.scene-render.v1' AND "
    "content_jsonb->>'stage' IN ('writer','rewrite_1','rewrite_2','polished','a"
    "ccepted') AND artifact_key = 'compiler.scene_render.' || (content_jsonb->>"
    "'scene_id') || '.' || (content_jsonb->>'stage')) OR (artifact_kind = 'vali"
    "dation_report' AND schema_id = 'compiler.prose-judge-report.v1' AND conten"
    "t_jsonb->>'role' IN ('fidelity','adversarial','coherence','arbiter') AND a"
    "rtifact_key IN ('compiler.validation_report.' || (content_jsonb->>'scene_i"
    "d') || '.semantic_0.' || (content_jsonb->>'role'),'compiler.validation_rep"
    "ort.' || (content_jsonb->>'scene_id') || '.semantic_1.' || (content_jsonb-"
    ">>'role'),'compiler.validation_report.' || (content_jsonb->>'scene_id') ||"
    " '.semantic_2.' || (content_jsonb->>'role'),'compiler.validation_report.' "
    "|| (content_jsonb->>'scene_id') || '.preservation.' || (content_jsonb->>'r"
    "ole'))) OR (artifact_kind = 'validation_report' AND schema_id = 'compiler."
    "prose-consensus-report.v1' AND artifact_key IN ('compiler.validation_repor"
    "t.' || (content_jsonb->>'scene_id') || '.semantic_' || (content_jsonb->>'r"
    "ound') || '.consensus', 'compiler.validation_report.' || (content_jsonb->>"
    "'scene_id') || '.preservation.consensus')) OR (artifact_kind = 'validation"
    "_report' AND schema_id = 'compiler.prose-quality-report.v1' AND ((content_"
    "jsonb->>'report_kind' = 'findings' AND artifact_key = 'compiler.validation"
    "_report.' || (content_jsonb->>'scene_id') || '.quality.findings') OR (cont"
    "ent_jsonb->>'report_kind' = 'pairwise' AND ((content_jsonb->'position_mapp"
    "ing'->>'a' = 'original' AND artifact_key = 'compiler.validation_report.' |"
    "| (content_jsonb->>'scene_id') || '.quality.pairwise.original_first') OR ("
    "content_jsonb->'position_mapping'->>'a' = 'polished' AND artifact_key = 'c"
    "ompiler.validation_report.' || (content_jsonb->>'scene_id') || '.quality.p"
    "airwise.polished_first'))))) OR (artifact_kind = 'novel_candidate' AND art"
    "ifact_key = 'compiler.novel_candidate' AND schema_id = 'compiler.novel-can"
    "didate.v1') OR (artifact_kind = 'compile_manifest' AND artifact_key = 'com"
    "piler.compile_manifest' AND schema_id = 'compiler.compile-manifest.v1'))))"
    ", false)) OR ((artifact_kind IN ('scene_render','validation_report','compi"
    "le_manifest')) AND artifact_key ~ '\\.attempt_[1-9][0-9]*$' AND COALESCE((("
    "artifact_kind = 'input_manifest' AND regexp_replace(artifact_key, '\\.attem"
    "pt_[1-9][0-9]*$', '') = 'compiler.input_manifest' AND schema_id = 'compile"
    "r.input-manifest.v1') OR (artifact_kind = 'narrative_ir' AND regexp_replac"
    "e(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.narrative_ir' AN"
    "D schema_id = 'compiler.narrative-ir.v1') OR (artifact_kind = 'novel_plan'"
    " AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compile"
    "r.novel_plan' AND schema_id = 'compiler.novel-plan.v1') OR (artifact_kind "
    "= 'scene_plan' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', "
    "'') = 'compiler.scene_plan' AND schema_id IN ('compiler.scene-plan.v1', 'c"
    "ompiler.scene-plan.v2')) OR (content_jsonb->>'schema_id' = schema_id AND ("
    "(artifact_kind = 'scene_context' AND schema_id = 'compiler.prose-judge-che"
    "cklist.v1' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') "
    "= 'compiler.scene_context.' || (content_jsonb->>'scene_id')) OR (artifact_"
    "kind = 'scene_render' AND schema_id = 'compiler.scene-render.v1' AND conte"
    "nt_jsonb->>'stage' IN ('writer','rewrite_1','rewrite_2','polished','accept"
    "ed') AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'com"
    "piler.scene_render.' || (content_jsonb->>'scene_id') || '.' || (content_js"
    "onb->>'stage')) OR (artifact_kind = 'validation_report' AND schema_id = 'c"
    "ompiler.prose-judge-report.v1' AND content_jsonb->>'role' IN ('fidelity','"
    "adversarial','coherence','arbiter') AND regexp_replace(artifact_key, '\\.at"
    "tempt_[1-9][0-9]*$', '') IN ('compiler.validation_report.' || (content_jso"
    "nb->>'scene_id') || '.semantic_0.' || (content_jsonb->>'role'),'compiler.v"
    "alidation_report.' || (content_jsonb->>'scene_id') || '.semantic_1.' || (c"
    "ontent_jsonb->>'role'),'compiler.validation_report.' || (content_jsonb->>'"
    "scene_id') || '.semantic_2.' || (content_jsonb->>'role'),'compiler.validat"
    "ion_report.' || (content_jsonb->>'scene_id') || '.preservation.' || (conte"
    "nt_jsonb->>'role'))) OR (artifact_kind = 'validation_report' AND schema_id"
    " = 'compiler.prose-consensus-report.v1' AND regexp_replace(artifact_key, '"
    "\\.attempt_[1-9][0-9]*$', '') IN ('compiler.validation_report.' || (content"
    "_jsonb->>'scene_id') || '.semantic_' || (content_jsonb->>'round') || '.con"
    "sensus', 'compiler.validation_report.' || (content_jsonb->>'scene_id') || "
    "'.preservation.consensus')) OR (artifact_kind = 'validation_report' AND sc"
    "hema_id = 'compiler.prose-quality-report.v1' AND ((content_jsonb->>'report"
    "_kind' = 'findings' AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]"
    "*$', '') = 'compiler.validation_report.' || (content_jsonb->>'scene_id') |"
    "| '.quality.findings') OR (content_jsonb->>'report_kind' = 'pairwise' AND "
    "((content_jsonb->'position_mapping'->>'a' = 'original' AND regexp_replace("
    "artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.validation_report."
    "' || (content_jsonb->>'scene_id') || '.quality.pairwise.original_first') O"
    "R (content_jsonb->'position_mapping'->>'a' = 'polished' AND regexp_replace"
    "(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.validation_report"
    ".' || (content_jsonb->>'scene_id') || '.quality.pairwise.polished_first'))"
    "))) OR (artifact_kind = 'novel_candidate' AND regexp_replace(artifact_key,"
    " '\\.attempt_[1-9][0-9]*$', '') = 'compiler.novel_candidate' AND schema_id "
    "= 'compiler.novel-candidate.v1') OR (artifact_kind = 'compile_manifest' AN"
    "D regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compiler.c"
    "ompile_manifest' AND schema_id = 'compiler.compile-manifest.v1')))), false"
    ")) OR COALESCE((artifact_kind = 'validation_report' AND schema_id = 'compi"
    "ler.prose-continuity-review.v1' AND content_jsonb->>'schema_id' = schema_i"
    "d AND regexp_replace(artifact_key, '\\.attempt_[1-9][0-9]*$', '') = 'compil"
    "er.continuity.' || (content_jsonb->>'scene_id')), false)) OR COALESCE((art"
    "ifact_kind = 'validation_report' AND schema_id = 'compiler.prose-revision-"
    "decision.v1' AND content_jsonb->>'schema_id' = schema_id AND content_jsonb"
    "->>'input_hash' ~ '^[0-9a-f]{64}$' AND regexp_replace(artifact_key, '\\.att"
    "empt_[1-9][0-9]*$', '') = 'compiler.validation_report.' || (content_jsonb-"
    ">>'scene_id') || '.revision.' || (content_jsonb->>'input_hash')), false)"
)


def _replace(expression: str) -> None:
    op.drop_constraint(
        op.f("ck_compile_artifacts_identity_allowed"), "compile_artifacts", type_="check"
    )
    op.create_check_constraint(
        op.f("ck_compile_artifacts_identity_allowed"), "compile_artifacts", expression
    )


def upgrade() -> None:
    _replace(NEW_IDENTITY)


def downgrade() -> None:
    # Existing editorial evidence makes downgrade fail atomically; never delete it.
    _replace(OLD_IDENTITY)
